### PR TITLE
fixed up acceptance test

### PR DESCRIPTION
**Pull request by james-powis**
Change defaults to use nodes[0] for puppet agent run, also removing stub docker as it is no longer needed.

### CODE REVIEW

**Comment by nibalizer** [comment]
I don't think you can just remove the file managed by modulesync, since the next msync will just put it back

**Comment by james-powis** [comment]
@nibalizer I created this file via copy and then accidentally committed it... it was not actually provided by modulesync

**Comment by bbriggs** [comment]
Since you're working on acceptance tests, go ahead and slip something like this into your .sync.yml so we can have it included in Travis: https://github.com/voxpupuli/puppet-corosync/blob/master/.sync.yml

**Review by bbriggs — CHANGES_REQUESTED** [review]
Add acceptance tests to travis

**Review by bbriggs — APPROVED** [review]

**Pull request merged**
