### PR TITLE
modulesync 0.16.4

### PR DESCRIPTION
**Pull request by james-powis**

### CODE REVIEW

**Comment by james-powis** [comment]
Those redundant selfs are a not quite redundant... from my interpretation of the puppet report api

**Comment by james-powis** [comment]
It should be mentioned that the module_sync nodesets are NOT compatiable with this module, they need 

```yaml
roles:
  - master
```

added to them

**Comment by james-powis** [comment]
Logged https://github.com/voxpupuli/modulesync_config/issues/287 to track the module sync issues observed

**Comment by sacres** [comment]
@james-powis  and I discussed his great work so far on IRC. The README.md needs some loving (I'd crack at it but have never touched this module)
@bastelfreak

**Comment by james-powis** [comment]
Readme Updated and Cleaned up

**Review by bbriggs — APPROVED** [review]
LGTM, we just want to make sure that the next msync won't clobber your changes to the acceptance test nodesets (if you changed them yourself that is)

**Comment by dhoppe** [comment]
The first msync should not hurt and all mentioned issues can be fixed afterwards.

**Pull request merged**
