### PR TITLE
Remove duplicate CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by dhoppe**

### CODE REVIEW

**Comment by ekohl** [comment]
This module needs a modulesync as well.

**Comment by dhoppe** [comment]
@ekohl Oh. I must have misused Vox Pupuli Tasks. There are a lot of modules which require a modulesync.

**Comment by ekohl** [comment]
https://github.com/voxpupuli/puppet-report_hipchat/issues/44

**Comment by dhoppe** [comment]
Modulesync will take care of this:
* https://github.com/voxpupuli/modulesync_config/blob/master/config_defaults.yml#L146-L147

**Pull request closed without merging**
